/**
 * File:
 *  defs.js
 *  
 * Notes:
 *  Server side constant definitions  
 *  
 * History:
 *  2013/09/15 Written by Simon Platten
 */
var ANSI_PREFIX           = "\u001b["
   ,CRLF                  = "\r\n"
   ,RED                   = ANSI_PREFIX + "31m" 
   ,GREEN                 = ANSI_PREFIX + "32m" 
   ,YELLOW                = ANSI_PREFIX + "33m"
   ,BLUE                  = ANSI_PREFIX + "34m"
   ,MAGENTA               = ANSI_PREFIX + "35m"
   ,CYAN                  = ANSI_PREFIX + "36m" 
   ,RESET                 = ANSI_PREFIX + "0m"
   ,CLRSCR                = ANSI_PREFIX + "2J" + ANSI_PREFIX + "0;0f"
   ,RESTCP                = ANSI_PREFIX + "u"
   ,SAVECP                = ANSI_PREFIX + "s"
   ,ARG_AUDITID           = "aid"
   ,ARG_COMPANY           = "cmpy"
   ,ARG_CONTENT           = "cnt"
   ,ARG_LOGOUT            = "logout"
   ,ARG_PAGE              = "pg"
   ,ARG_WEEKID            = "wid"
   ,CFG_PREFIX_EAHOD      = "EAHOD:"
   ,CFG_PREFIX_SMTP       = "SMTP:"
   ,CFG_PREFIX_VAR        = "VAR:"
   ,CHECK_DB_FOR_ERRORS   = (1000 * 10) //30 minutes (When ack complete change to 10 seconds)
   ,CONTENT_LOGIN         = "login"
   ,DAYS_IN_WEEK          = 7
   ,DAYS_IN_YEAR          = 365
   ,DAYS_OF_WEEK          = "dysofwk"      
   ,FORM_COMPANY          = "company"
   ,FORM_DATA             = " form-data;"
   ,FORM_LOGIN            = "login"
   ,ID_DOW_PREFIX         = "dow"
   ,INTERVAL_CHECK_CONFIG = 1111
   ,INTERVAL_CHECK_DB     = 5000
   ,INTERVAL_CHECK_ERRORS = 5000 
   ,INTERVAL_SRVCE_EMAILS = 30000   
   ,LIVE_OF_SESSION       = 86400
   ,OPMODE_CONFIGURATION  = 1
   ,OPMODE_CUSTOM_FIELDS  = 2
   ,OPMODE_DEPARTMENTS    = 3
   ,OPMODE_LOCATIONS      = 4
   ,OPMODE_PROJECTS       = 5
   ,OPMODE_ROLES          = 6
   ,OPMODE_TASKS          = 7
   ,OPMODE_USERS          = 8
   ,POST_STARTMARKER_PREFIX  = "-----------------------------"
   ,QUERY_TIMEOUT         = 10 * 1000
   ,REPORT_TIMEOUT        = 60 * 1000
   ,REPORT_TYPE_PROJECTS  = 0x01
   ,SCK_PORT              = 8000
   ,SCKMSG_APPROVE_TS     = "approvets"
   ,SCKMSG_CHECKIN        = "checkin"
   ,SCKMSG_CLEANUP_AUDITLOG = "clnupalog"
   ,SCKMSG_CLEANUP_PDF      = "clnuppdf"
   ,SCKMSG_CLEANUP_ERRORLOG = "clnupelog"
   ,SCKMSG_COMPANY_REPORT = "cmpyrpt"
   ,SCKMSG_CONNECT        = "connect"
   ,SCKMSG_CONNECTION     = "connection"
   ,SCKMSG_COPY_ACTIVITIES = "copyactivities"
   ,SCKMSG_CREATE_ACTIVITY = "createactivity"
   ,SCKMSG_CREATE_CUSTFLD = "createcusfld"
   ,SCKMSG_CREATE_DEPT    = "createdept"
   ,SCKMSG_CREATE_LOCATION = "createlocation"
   ,SCKMSG_CREATE_PDF     = "createpdf"
   ,SCKMSG_CREATE_PROJECT = "createproj"
   ,SCKMSG_CREATE_REPORT  = "createreport"
   ,SCKMSG_CREATE_ROLE    = "createrole"
   ,SCKMSG_CREATE_TASK    = "createtask"
   ,SCKMSG_CREATE_USER    = "createuser"
   ,SCKMSG_DATECTRL_CHGE  = "dtctrlchge"
   ,SCKMSG_DATA_SET       = "dataset"   
   ,SCKMSG_DATE_INFO      = "dateinfo"
   ,SCKMSG_DATE_RESPONSE  = "dateresp"
   ,SCKMSG_DELETE_ACTIVITY = "delactivity"
   ,SCKMSG_DELETE_LOCATIONS = "delloc"
   ,SCKMSG_DELETE_DEPTS   = "deldepts"
   ,SCKMSG_DELETE_PROJECTS = "delproj"
   ,SCKMSG_DELETE_ROLES   = "delroles"
   ,SCKMSG_DELETE_TASKS   = "deltasks"
   ,SCKMSG_DISCONNECT     = "disconnect"
   ,SCKMSG_DISMISS_ERROR  = "dismisserr"
   ,SCKMSG_ERROR          = "errcode"
   ,SCKMSG_FORCE_REFRESH  = "forcerefresh"
   ,SCKMSG_GET_DATE       = "getdate"
   ,SCKMSG_INDIVIDUAL     = "individual"
   ,SCKMSG_LOOKUP_REQ     = "reqlkup"
   ,SCKMSG_LOOKUP_RESP    = "resplkup"
   ,SCKMSG_MESSAGE        = "message"
   ,SCKMSG_LIST_ACTIVITIES = "lstactivities"//CAN THIS BE DELETED?
   ,SCKMSG_LIST_CMPY      = "lstcmpy"
   ,SCKMSG_LIST_CONFIG    = "lstcfg"	//CAN THIS BE DELETED?
   ,SCKMSG_LIST_CUSTFLDS  = "lstcustflds"//CAN THIS BE DELETED?
   ,SCKMSG_LIST_DEPT      = "lstdept"//CAN THIS BE DELETED?
   ,SCKMSG_LIST_LASTMNTHS = "lstlastmnths"
   ,SCKMSG_LIST_LICENSE   = "lstlic"
   ,SCKMSG_LIST_LOCATIONS = "lstlocs"//CAN THIS BE DELETED?
   ,SCKMSG_LIST_PEOPLE    = "lstpeople"//CAN THIS BE DELETED?
   ,SCKMSG_LIST_PERMS     = "lstperms"
   ,SCKMSG_LIST_PROJ      = "lstproj"
   ,SCKMSG_LIST_PROJRPT   = "projrpt"
   ,SCKMSG_LIST_REPORTS   = "lstreports"
   ,SCKMSG_LIST_REQACTY   = "reqactivities"//CAN THIS BE DELETED?
//HACK   ,SCKMSG_LIST_REQCFG    = "reqcfg"
//HACK   ,SCKMSG_LIST_REQCFLDLST = "reqcustfldlst"
   ,SCKMSG_LIST_REQCMPY   = "reqcmpy"
//HACK   ,SCKMSG_LIST_REQDEPT   = "reqdepts"   
   ,SCKMSG_LIST_REQLIC    = "reqlic"
   ,SCKMSG_LIST_REQLOC    = "reqloc"
   ,SCKMSG_LIST_REQPEOPLE = "reqpeople"
   ,SCKMSG_LIST_REQPERMS  = "reqperms"
   ,SCKMSG_LIST_REQPROJ   = "reqproj"
   ,SCKMSG_LIST_REQROLE   = "reqroles"
   ,SCKMSG_LIST_REQREPORTS= "reqreports"
   ,SCKMSG_LIST_REQTASKS  = "reqtasks"
   ,SCKMSG_LIST_REQTSSUM  = "reqtslist"
   ,SCKMSG_LIST_RESPONSE  = "listresp"
   ,SCKMSG_LIST_ROLES     = "lstroles"
   ,SCKMSG_LIST_TASKS     = "lsttasks"
   ,SCKMSG_LIST_TSREVIEW  = "tsreview"
   ,SCKMSG_PDF			  = "pdf"
   ,SCKMSG_PERSONAL_SUMMARY = "persummary"
   ,SCKMSG_PERMS_UPDATED  = "permsupdated"
   ,SCKMSG_PROCESS_DATE   = "procdate"
   ,SCKMSG_REJECT_TS      = "rejectts"
   ,SCKMSG_RELOAD         = "reload"
   ,SCKMSG_REPORT_AS_CSV  = "rptascsv"
   ,SCKMSG_REQCMPY_REPORT = "reqcmprpt"
   ,SCKMSG_REQUEST_LIST   = "reqlist"
   ,SCKMSG_REQUNUSD_DEPTS = "requnusddepts"
   ,SCKMSG_REQUNUSD_LOCATIONS = "requnusedlocs"
   ,SCKMSG_REQUNUSD_PROJECTS = "requnusdprojects" 
   ,SCKMSG_REQUNUSD_ROLES = "requnusdroles"
   ,SCKMSG_REQUNUSD_TASKS = "requnusdtasks"
   ,SCKMSG_REQUSER_INFO   = "requsrinfo"
   ,SCKMSG_SAVEAS_CSV     = "saveascsv"
   ,SCKMSG_SU_MODIFY      = "sumodify"
   ,SCKMSG_UNUSED_DEPTS   = "unusddepts"
   ,SCKMSG_UNUSED_LOCATIONS = "unusdlocs"
   ,SCKMSG_UNUSED_PROJECTS = "unusdprojects"
   ,SCKMSG_UNUSED_ROLES   = "unusdroles"
   ,SCKMSG_UNUSED_TASKS   = "unusedtasks"
   ,SCKMSG_UPDATE_CONFIG  = "updtconfig"
   ,SCKMSG_UPDATE_PERMS   = "updateperms"
   ,SCKMSG_UPDATE_USER    = "updateuser"
   ,SCKMSG_USER_INFO      = "userinfo"
   ,SERVER_HOST_NAME      = "Intranet Server Address"
   ,SHOW_CONTENT_FN       = "function showContent()"
   ,SMTP_ALL_FROM_ONE_ADDR = CFG_PREFIX_SMTP + "All from one address"  
   ,SMTP_AUTH_PASSWORD    = CFG_PREFIX_SMTP + "Auth password"
   ,SMTP_AUTH_USR         = CFG_PREFIX_SMTP + "Auth user"
   ,SMTP_SERVER_ADDRESS   = CFG_PREFIX_SMTP + "Server address/name"
   ,SMTP_SERVER_PORT      = CFG_PREFIX_SMTP + "Server port"
   ,SMTP_TSLSSL           = CFG_PREFIX_SMTP + "TSL/SSL"
   ,STS_ACTIVE            = "Active"
   ,STS_WFA               = "Waiting for approval"
   ,STS_APPRVD            = "Approved"
   ,STS_RJTD              = "Rejected"
   ,STS_UNKWN             = "Unknown"
   ,UPLOADS				  = "/uploads/"
   ,VAR_DATE_FORMAT       = CFG_PREFIX_VAR + "Date Format"
   ,VAR_FIRST_DAY_OF_YEAR = CFG_PREFIX_VAR + "First day of year"
   ,VAR_FIRST_DAY_OF_WEEK = CFG_PREFIX_VAR + "First day of week"
   ,VAR_TIMESHEET_LOGO    = CFG_PREFIX_VAR + "Timesheet logo"
   ,WILDCARD_IDX          = 4;
try{
  if ( exports !== undefined ) {
    exports.ANSI                  = ANSI_PREFIX;
    exports.RED                   = RED; 
    exports.GREEN                 = GREEN; 
    exports.YELLOW                = YELLOW;
    exports.BLUE                  = BLUE;
    exports.MAGENTA               = MAGENTA;
    exports.CYAN                  = CYAN; 
    exports.RESET                 = RESET;
    exports.CLRSCR                = CLRSCR;
    exports.RESTCP                = RESTCP;
    exports.SAVECP                = SAVECP;
    exports.ARG_AUDITID           = ARG_AUDITID;
    exports.ARG_COMPANY           = ARG_COMPANY;
    exports.ARG_CONTENT           = ARG_CONTENT;
    exports.ARG_LOGOUT            = ARG_LOGOUT;
    exports.ARG_PAGE              = ARG_PAGE;
    exports.ARG_WEEKID            = ARG_WEEKID;
    exports.CFG_PREFIX_EAHOD      = CFG_PREFIX_EAHOD;
    exports.CFG_PREFIX_SMTP       = CFG_PREFIX_SMTP;
    exports.CFG_PREFIX_VAR        = CFG_PREFIX_VAR;            
    exports.CHECK_DB_FOR_ERRORS   = CHECK_DB_FOR_ERRORS;
    exports.CONTENT_LOGIN         = CONTENT_LOGIN;
    exports.DAYS_IN_WEEK          = DAYS_IN_WEEK;
    exports.DAYS_IN_YEAR          = DAYS_IN_YEAR;
    exports.DAYS_OF_WEEK          = DAYS_OF_WEEK;
    exports.FORM_COMPANY          = FORM_COMPANY;  
    exports.FORM_DATA             = FORM_DATA;
    exports.FORM_LOGIN            = FORM_LOGIN;
    exports.ID_DOW_PREFIX         = ID_DOW_PREFIX;
    exports.INTERVAL_CHECK_CONFIG = INTERVAL_CHECK_CONFIG;
    exports.INTERVAL_CHECK_DB     = INTERVAL_CHECK_DB;
    exports.INTERVAL_CHECK_ERRORS = INTERVAL_CHECK_ERRORS;
    exports.INTERVAL_SRVCE_EMAILS = INTERVAL_SRVCE_EMAILS;
    exports.LIVE_OF_SESSION       = LIVE_OF_SESSION;  
    exports.OPMODE_CONFIGURATION  = OPMODE_CONFIGURATION;
    exports.OPMODE_CUSTOM_FIELDS  = OPMODE_CUSTOM_FIELDS;
    exports.OPMODE_DEPARTMENTS    = OPMODE_DEPARTMENTS;
    exports.OPMODE_LOCATIONS      = OPMODE_LOCATIONS;
    exports.OPMODE_PROJECTS       = OPMODE_PROJECTS;
    exports.OPMODE_ROLES          = OPMODE_ROLES;
    exports.OPMODE_TASKS          = OPMODE_TASKS;
    exports.OPMODE_USERS          = OPMODE_USERS;    
    exports.POST_STARTMARKER_PREFIX = POST_STARTMARKER_PREFIX;
    exports.QUERY_TIMEOUT         = QUERY_TIMEOUT;
    exports.REPORT_TIMEOUT        = REPORT_TIMEOUT;
    exports.REPORT_TYPE_PROJECTS  = REPORT_TYPE_PROJECTS;
    exports.SCK_PORT              = SCK_PORT;
    exports.SCKMSG_CHECKIN        = SCKMSG_CHECKIN;   
    exports.SCKMSG_APPROVE_TS     = SCKMSG_APPROVE_TS;
    exports.SCKMSG_CLEANUP_AUDITLOG = SCKMSG_CLEANUP_AUDITLOG;
    exports.SCKMSG_CLEANUP_PDF      = SCKMSG_CLEANUP_PDF
    exports.SCKMSG_CLEANUP_ERRORLOG = SCKMSG_CLEANUP_ERRORLOG;
    exports.SCKMSG_COMPANY_REPORT = SCKMSG_COMPANY_REPORT;   
    exports.SCKMSG_CONNECT        = SCKMSG_CONNECT;
    exports.SCKMSG_CONNECTION     = SCKMSG_CONNECTION;
    exports.SCKMSG_COPY_ACTIVITIES = SCKMSG_COPY_ACTIVITIES;
    exports.SCKMSG_CREATE_ACTIVITY = SCKMSG_CREATE_ACTIVITY;
    exports.SCKMSG_CREATE_CUSTFLD = SCKMSG_CREATE_CUSTFLD;   
    exports.SCKMSG_CREATE_DEPT    = SCKMSG_CREATE_DEPT;
    exports.SCKMSG_CREATE_LOCATION = SCKMSG_CREATE_LOCATION;
	exports.SCKMSG_CREATE_PDF     = SCKMSG_CREATE_PDF;
    exports.SCKMSG_CREATE_PROJECT = SCKMSG_CREATE_PROJECT;
    exports.SCKMSG_CREATE_REPORT  = SCKMSG_CREATE_REPORT; 
    exports.SCKMSG_CREATE_ROLE    = SCKMSG_CREATE_ROLE;
    exports.SCKMSG_CREATE_TASK    = SCKMSG_CREATE_TASK;    
    exports.SCKMSG_CREATE_USER    = SCKMSG_CREATE_USER;
	exports.SCKMSG_DATECTRL_CHGE  = SCKMSG_DATECTRL_CHGE;
    exports.SCKMSG_DATA_SET       = SCKMSG_DATA_SET;     
    exports.SCKMSG_DATE_INFO      = SCKMSG_DATE_INFO;
    exports.SCKMSG_DATE_RESPONSE  = SCKMSG_DATE_RESPONSE;
    exports.SCKMSG_DELETE_ACTIVITY = SCKMSG_DELETE_ACTIVITY;
    exports.SCKMSG_DELETE_LOCATIONS = SCKMSG_DELETE_LOCATIONS;
    exports.SCKMSG_DELETE_DEPTS   = SCKMSG_DELETE_DEPTS;
    exports.SCKMSG_DELETE_PROJECTS = SCKMSG_DELETE_PROJECTS;
    exports.SCKMSG_DELETE_ROLES   = SCKMSG_DELETE_ROLES;
    exports.SCKMSG_DELETE_TASKS   = SCKMSG_DELETE_TASKS;
    exports.SCKMSG_DISCONNECT     = SCKMSG_DISCONNECT;
    exports.SCKMSG_DISMISS_ERROR  = SCKMSG_DISMISS_ERROR;
    exports.SCKMSG_ERROR          = SCKMSG_ERROR;
    exports.SCKMSG_FORCE_REFRESH  = SCKMSG_FORCE_REFRESH;
	exports.SCKMSG_GET_DATE       = SCKMSG_GET_DATE;
    exports.SCKMSG_INDIVIDUAL     = SCKMSG_INDIVIDUAL;
    exports.SCKMSG_LOOKUP_REQ     = SCKMSG_LOOKUP_REQ;
    exports.SCKMSG_LOOKUP_RESP    = SCKMSG_LOOKUP_RESP;
    exports.SCKMSG_MESSAGE        = SCKMSG_MESSAGE;
    exports.SCKMSG_LIST_ACTIVITIES = SCKMSG_LIST_ACTIVITIES;//CAN THIS BE DELETED?
    exports.SCKMSG_LIST_CMPY      = SCKMSG_LIST_CMPY;
    exports.SCKMSG_LIST_CONFIG    = SCKMSG_LIST_CONFIG;//CAN THIS BE DELETED?
    exports.SCKMSG_LIST_CUSTFLDS  = SCKMSG_LIST_CUSTFLDS;//CAN THIS BE DELETED?
    exports.SCKMSG_LIST_DEPT      = SCKMSG_LIST_DEPT;//CAN THIS BE DELETED?
    exports.SCKMSG_LIST_LASTMNTHS = SCKMSG_LIST_LASTMNTHS;
    exports.SCKMSG_LIST_LICENSE   = SCKMSG_LIST_LICENSE;
    exports.SCKMSG_LIST_LOCATIONS = SCKMSG_LIST_LOCATIONS;//CAN THIS BE DELETED?
    exports.SCKMSG_LIST_PEOPLE    = SCKMSG_LIST_PEOPLE;//CAN THIS BE DELETED?
    exports.SCKMSG_LIST_PERMS     = SCKMSG_LIST_PERMS;
    exports.SCKMSG_LIST_PROJ      = SCKMSG_LIST_PROJ;
    exports.SCKMSG_LIST_PROJRPT   = SCKMSG_LIST_PROJRPT;
    exports.SCKMSG_LIST_REPORTS   = SCKMSG_LIST_REPORTS;
    exports.SCKMSG_LIST_REQACTY   = SCKMSG_LIST_REQACTY;//CAN THIS BE DELETED?
//HACK    exports.SCKMSG_LIST_REQCFG    = SCKMSG_LIST_REQCFG;
//HACK    exports.SCKMSG_LIST_REQCFLDLST = SCKMSG_LIST_REQCFLDLST;
    exports.SCKMSG_LIST_REQCMPY   = SCKMSG_LIST_REQCMPY;
//HACK    exports.SCKMSG_LIST_REQDEPT   = SCKMSG_LIST_REQDEPT;
    exports.SCKMSG_LIST_REQLIC    = SCKMSG_LIST_REQLIC;
    exports.SCKMSG_LIST_REQLOC    = SCKMSG_LIST_REQLOC;
    exports.SCKMSG_LIST_REQPEOPLE = SCKMSG_LIST_REQPEOPLE;
    exports.SCKMSG_LIST_REQPERMS  = SCKMSG_LIST_REQPERMS;
    exports.SCKMSG_LIST_REQPROJ   = SCKMSG_LIST_REQPROJ;
    exports.SCKMSG_LIST_REQROLE   = SCKMSG_LIST_REQROLE;
    exports.SCKMSG_LIST_REQREPORTS= SCKMSG_LIST_REQREPORTS;
    exports.SCKMSG_LIST_REQTASKS  = SCKMSG_LIST_REQTASKS;
    exports.SCKMSG_LIST_REQTSSUM  = SCKMSG_LIST_REQTSSUM;
    exports.SCKMSG_LIST_RESPONSE  = SCKMSG_LIST_RESPONSE;
    exports.SCKMSG_LIST_ROLES     = SCKMSG_LIST_ROLES;
    exports.SCKMSG_LIST_TASKS     = SCKMSG_LIST_TASKS;
    exports.SCKMSG_LIST_TSREVIEW  = SCKMSG_LIST_TSREVIEW;
	exports.SCKMSG_PDF            = SCKMSG_PDF;
    exports.SCKMSG_PERSONAL_SUMMARY = SCKMSG_PERSONAL_SUMMARY;
    exports.SCKMSG_PERMS_UPDATED  = SCKMSG_PERMS_UPDATED;
    exports.SCKMSG_PROCESS_DATE   = SCKMSG_PROCESS_DATE;
    exports.SCKMSG_REJECT_TS      = SCKMSG_REJECT_TS;
    exports.SCKMSG_RELOAD         = SCKMSG_RELOAD;
    exports.SCKMSG_REPORT_AS_CSV  = SCKMSG_REPORT_AS_CSV;
    exports.SCKMSG_REQCMPY_REPORT = SCKMSG_REQCMPY_REPORT;
    exports.SCKMSG_REQUEST_LIST   = SCKMSG_REQUEST_LIST;
    exports.SCKMSG_REQUNUSD_DEPTS = SCKMSG_REQUNUSD_DEPTS;
    exports.SCKMSG_REQUNUSD_LOCATIONS = SCKMSG_REQUNUSD_LOCATIONS;
    exports.SCKMSG_REQUNUSD_PROJECTS = SCKMSG_REQUNUSD_PROJECTS; 
    exports.SCKMSG_REQUNUSD_ROLES = SCKMSG_REQUNUSD_ROLES;
    exports.SCKMSG_REQUNUSD_TASKS = SCKMSG_REQUNUSD_TASKS;
    exports.SCKMSG_REQUSER_INFO   = SCKMSG_REQUSER_INFO;
    exports.SCKMSG_SAVEAS_CSV     = SCKMSG_SAVEAS_CSV;
    exports.SCKMSG_SU_MODIFY      = SCKMSG_SU_MODIFY;
    exports.SCKMSG_UNUSED_DEPTS   = SCKMSG_UNUSED_DEPTS;
    exports.SCKMSG_UNUSED_LOCATIONS = SCKMSG_UNUSED_LOCATIONS;
    exports.SCKMSG_UNUSED_PROJECTS = SCKMSG_UNUSED_PROJECTS;
    exports.SCKMSG_UNUSED_ROLES   = SCKMSG_UNUSED_ROLES;
    exports.SCKMSG_UNUSED_TASKS   = SCKMSG_UNUSED_TASKS;
    exports.SCKMSG_UPDATE_CONFIG  = SCKMSG_UPDATE_CONFIG;
    exports.SCKMSG_UPDATE_PERMS   = SCKMSG_UPDATE_PERMS;
    exports.SCKMSG_UPDATE_USER    = SCKMSG_UPDATE_USER;
    exports.SCKMSG_USER_INFO      = SCKMSG_USER_INFO;
    exports.SERVER_HOST_NAME      = SERVER_HOST_NAME;
    exports.SHOW_CONTENT_FN       = SHOW_CONTENT_FN;
    exports.SMTP_ALL_FROM_ONE_ADDR = SMTP_ALL_FROM_ONE_ADDR; 
    exports.SMTP_AUTH_PASSWORD    = SMTP_AUTH_PASSWORD;
    exports.SMTP_AUTH_USR         = SMTP_AUTH_USR;
    exports.SMTP_SERVER_ADDRESS   = SMTP_SERVER_ADDRESS;
    exports.SMTP_SERVER_PORT      = SMTP_SERVER_PORT;
    exports.SMTP_TSLSSL           = SMTP_TSLSSL;
    exports.STS_ACTIVE            = STS_ACTIVE;
    exports.STS_WFA               = STS_WFA;
    exports.STS_APPRVD            = STS_APPRVD;
    exports.STS_RJTD              = STS_RJTD;
    exports.STS_UNKWN             = STS_UNKWN;   
	exports.UPLOADS				  = UPLOADS; 
    exports.VAR_DATE_FORMAT       = VAR_DATE_FORMAT;
    exports.VAR_FIRST_DAY_OF_YEAR = VAR_FIRST_DAY_OF_YEAR;
    exports.VAR_FIRST_DAY_OF_WEEK = VAR_FIRST_DAY_OF_WEEK;   
	exports.VAR_TIMESHEET_LOGO    = VAR_TIMESHEET_LOGO;  
  }
} catch( ex ) {
//Client side
  //console.log("defs.js, client side: " + ex);
}      